# Generated by Django 5.0.1 on 2024-01-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=50)),
                ('pret', models.FloatField()),
                ('stoc', models.CharField(max_length=1024)),
                ('imagine', models.FileField(upload_to='')),
            ],
        ),
    ]
