# Generated by Django 5.0.1 on 2024-01-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produs',
            name='descriere',
            field=models.CharField(default='No description provided', max_length=1024),
        ),
        migrations.AlterField(
            model_name='produs',
            name='stoc',
            field=models.IntegerField(default=0),
        ),
    ]
