# Generated by Django 5.0.1 on 2024-01-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_produs_pret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produs',
            name='descriere',
            field=models.CharField(blank=True, default='No description provided', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='produs',
            name='imagine',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
