# Generated by Django 5.0.1 on 2024-01-23 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_student_an'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recenzie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('descriere', models.CharField(blank=True, default='No description provided', help_text='Intoduceti o descriere', max_length=1024, null=True)),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produs')),
            ],
        ),
    ]
