# Generated by Django 5.0.1 on 2024-01-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_elev_elevcurse'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ElevCurse',
            new_name='ElevCurs',
        ),
        migrations.AddField(
            model_name='elev',
            name='cursuri',
            field=models.ManyToManyField(through='app.ElevCurs', to='app.curs'),
        ),
    ]
