# Generated by Django 5.0.1 on 2024-01-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_elevcurse_elevcurs_elev_cursuri'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=50)),
                ('continut', models.CharField(blank=True, default='No description provided', help_text='Intoduceti o descriere', max_length=1024, null=True)),
                ('visible_from', models.DateTimeField()),
                ('end_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
