# Generated by Django 5.0.1 on 2024-01-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='continut',
            field=models.CharField(max_length=300),
        ),
    ]
