# Generated by Django 5.0.1 on 2024-01-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_post_continut'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-visible_from'], 'verbose_name': 'Postare', 'verbose_name_plural': 'Postari'},
        ),
        migrations.AlterField(
            model_name='post',
            name='continut',
            field=models.CharField(max_length=1024),
        ),
    ]
