# Generated by Django 5.0.1 on 2024-01-25 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_post_options_alter_post_continut'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-visible_from']},
        ),
        migrations.AlterUniqueTogether(
            name='elev',
            unique_together={('nume', 'prenume')},
        ),
    ]
