# Generated by Django 5.0.1 on 2024-01-29 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_post_managers_post_created_post_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-updated',)},
        ),
    ]
