# Generated by Django 5.0.1 on 2024-02-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_intrebare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intrebare',
            name='text_raspuns',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
